environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"
      SEABREEZE_ARCH: "x86"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      SEABREEZE_ARCH: "x64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - cmd: "mkdir dist"
  - cmd: cd "SeaBreeze"
  - ps: 'cat os-support\\windows\\VisualStudio2012\\VSProj\\SeaBreeze.rc | % { $_ -replace "afxres.h","windows.h" } > SeaBreeze.rc.new'
  - ps: 'cat SeaBreeze.rc.new | select-string -pattern "afxres.rc" -notmatch > SeaBreeze.rc.new2'
  - cmd: "MOVE /Y SeaBreeze.rc.new2 os-support\\windows\\VisualStudio2012\\VSProj\\SeaBreeze.rc"
  - cmd: msbuild.exe /p:Configuration=Debug /p:Platform=%SEABREEZE_ARCH% "os-support\\windows\\VisualStudio2012\\SeaBreeze.sln"
  - cmd: "COPY /Y os-support\\windows\\VisualStudio2012\\SetupWiX\\bin\\Debug\\SeaBreezeSetup-XXbit-vXYZ.msi ..\\dist\\SeaBreezeSetup-%PYTHON_ARCH%bit-%APPVEYOR_REPO_BRANCH%.msi"

build: off

test_script: off

after_test: off

artifacts:
  - path: dist\*.msi
    name: msi-installer

deploy:
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: 2jmPAIr0bDr/Aak6PsCtd5nRPQpHEKwjKN13k4fDp4f6fbibuLmGEkQspQguQwFe
  artifact: msi-installer
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
