environment:

  matrix:
    - SEABREEZE_ARCH: "Win32"
    - SEABREEZE_ARCH: "x64"

init:
  - "ECHO START"

install:
  - cmd: cd "SeaBreeze"
  - cmd: msbuild.exe /t:SeaBreeze /p:Configuration=Release /p:Platform=%SEABREEZE_ARCH% "os-support\\windows\\VisualStudio2015\\SeaBreeze.sln" 

build: off

test_script:
  - "ECHO done"

after_test:
  - "ECHO done"

artifacts:
  - path: SeaBreeze\lib
    name: seabreeze-lib-$(SEABREEZE_ARCH)
    type: zip

  - path: SeaBreeze\os-support\windows\windows-support
    name: seabreeze-drivers-$(SEABREEZE_ARCH)
    type: zip

deploy:
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: 2jmPAIr0bDr/Aak6PsCtd5nRPQpHEKwjKN13k4fDp4f6fbibuLmGEkQspQguQwFe
  artifact: seabreeze-lib-$(SEEBREEZE_ARCH),seabreeze-drivers-$(SEABREEZE_ARCH)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
